#
# Makefile for testing a slave Globule
#

TESTGROUPCONFS:=nomaster,nomaster \
		onemaster,onemasterA \
		onemaster,onemasterB \
		onemaster,onemasterC \
		onemaster,onemasterD \
		onemaster,onemasterE \
		onemaster,onemasterF \
		onemaster,onemasterG \
		onemaster,onemasterH \
		onemaster,onemasterI \
		onemaster,onemasterJ \
		onemaster,onemasterK \
		onemaster,onemasterL \
		onemaster,onemasterM 

include ../shared.mk

flood:: floodA1
