#
# Makefile for testing a master pSodium
#


TESTGROUPCONFS:=getslaveinfo,getslaveinfo \
		getdigests,getdigests \
		badpledge,getdigests \
		updateexpiry,updateexpiry \
		getmodif,getmodif \
		lyingclients,lyingclients \
		badslaves,lyingclients

include ../shared.mk


flood:: floodA1 floodA2
