#
# Makefile for testing a master Globule
#


TESTGROUPCONFS:=noslave,noslave \
	oneslave,oneslaveA \
	oneslave,oneslaveB \
	oneslave,oneslaveC \
	oneslave,oneslaveD \
	oneslave,oneslaveE \
	oneslave,oneslaveF \
	oneslave,oneslaveG \
	oneslave,oneslaveH \
	oneslave,oneslaveI \
	oneslave,oneslaveJ \
	oneslave,oneslaveK \
	oneslave,oneslaveL \
	oneslave,oneslaveM \
	servername,servername
		
include ../shared.mk


flood:: floodA1 floodA2
